version: "3"

services:
  pmd:
    image: wrapper/pmd
    build:
      context: ./../static-analysis-tools-wrappers
      dockerfile: ./apps/pmd/Dockerfile
    environment:
      PORT: 8090
    ports:
      - "8090:8090"
    restart: always
  eslint:
    image: wrapper/eslint
    build:
      context: ./../static-analysis-tools-wrappers
      dockerfile: ./apps/eslint/Dockerfile
    environment:
      PORT: 8091
    ports:
      - "8091:8091"
    restart: always
  checkstyle:
    image: wrapper/checkstyle
    build:
      context: ./../static-analysis-tools-wrappers
      dockerfile: ./apps/checkstyle/Dockerfile
    environment:
      PORT: 8092
    ports:
      - "8092:8092"
    restart: always
  infer:
    image: wrapper/infer
    build:
      context: ./../static-analysis-tools-wrappers
      dockerfile: ./apps/infer/Dockerfile
    environment:
      PORT: 8093
    ports:
      - "8093:8093"
    restart: always
  cppcheck:
    image: wrapper/cppcheck
    build:
      context: ./../static-analysis-tools-wrappers
      dockerfile: ./apps/cppcheck/Dockerfile
    environment:
      PORT: 8094
    ports:
      - "8094:8094"
    restart: always
