version: "3"

services:
  aggregator:
    image: sarif-aggregator
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - PMD_URL=http://wrapper/pmd:8090
      - ESLINT_URL=http://wrapper/eslint:8091
      - CHECKSTYLE_URL=http://wrapper/checkstyle:8092
      - INFER_URL=http://wrapper/infer:8093
      - CPPCHECK_URL=http://wrapper/cppcheck:8094
    ports:
      - "8080:8080"
