version: "3"

services:
  aggregator:
    image: aggregator-service
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/aggregator

      - PMD_URL=http://pmd:8090
      - ESLINT_URL=http://eslint:8091
      - CHECKSTYLE_URL=http://checkstyle:8092
      - INFER_URL=http://infer:8093
      - CPPCHECK_URL=http://cppcheck:8094
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - aggregator-postgres-volume:/var/lib/postgresql/data
      - ./database-init/:/docker-entrypoint-initdb.d/

  pmd:
    image: wrapper/pmd
    build:
      context: ./../static-analysis-tools-wrappers
      dockerfile: ./apps/pmd/Dockerfile
    environment:
      PORT: 8090
    ports:
      - "8090:8090"
  eslint:
    image: wrapper/eslint
    build:
      context: ./../static-analysis-tools-wrappers
      dockerfile: ./apps/eslint/Dockerfile
    environment:
      PORT: 8091
    ports:
      - "8091:8091"
  checkstyle:
    image: wrapper/checkstyle
    build:
      context: ./../static-analysis-tools-wrappers
      dockerfile: ./apps/checkstyle/Dockerfile
    environment:
      PORT: 8092
    ports:
      - "8092:8092"
  infer:
    image: wrapper/infer
    build:
      context: ./../static-analysis-tools-wrappers
      dockerfile: ./apps/infer/Dockerfile
    environment:
      PORT: 8093
    ports:
      - "8093:8093"
  cppcheck:
    image: wrapper/cppcheck
    build:
      context: ./../static-analysis-tools-wrappers
      dockerfile: ./apps/cppcheck/Dockerfile
    environment:
      PORT: 8094
    ports:
      - "8094:8094"
# include sonarqube


volumes:
  aggregator-postgres-volume: